import json

ID_FILE = 'src/locales/id/translation.json'
EN_FILE = 'src/locales/en/translation.json'

id_additions = {
    "dashboard": {
        "morning": "Selamat pagi",
        "afternoon": "Selamat siang",
        "evening": "Selamat sore",
        "night": "Selamat malam",
        "ready": "Siap untuk melanjutkan petualangan belajarmu hari ini?",
        "streak": "Streak",
        "days": "Hari",
        "level": "Level",
        "chapter_start": "Bab 01 — Mulai",
        "start_journey": "Mulai perjalanan",
        "learning": "belajarmu",
        "no_session_desc": "Belum ada sesi aktif. Buat kurikulum pertamamu dan biarkan Planner Agent menyusun jalur belajar yang dipersonalisasi untukmu.",
        "create_curriculum": "Buat Kurikulum",
        "passed": "Lulus",
        "all_topics": "Semua topik",
        "finished": "sudah selesai",
        "all_topics_desc": "Kamu sudah menyelesaikan semua materi yang tersedia. Saatnya review atau memulai topik baru.",
        "start_new_topic": "Mulai Topik Baru",
        "chapter_continue": "Bab {{num}} — Lanjutkan",
        "topics_count": "{{completed}} / {{total}} topik",
        "mins": "{{duration}} menit",
        "percent_finished": "{{progress}}% selesai",
        "continue_learning": "Lanjutkan Belajar",
        "start_now": "Mulai Sekarang",
        "view_curriculum": "Lihat kurikulum",
        "next_topic": "Topik berikutnya",
        "done": "Selesai",
        "quiz": "Kuis",
        "chat": "Chat",
        "history_activity": "Riwayat · Aktivitas",
        "recent_activity": "Aktivitas Terakhir",
        "view_all": "Lihat semua",
        "no_activity": "Belum ada aktivitas",
        "no_activity_desc": "Mulai belajar untuk melihat riwayat aktivitasmu di sini. Selesaikan modul atau ambil kuis untuk mulai mengisi riwayat.",
        "syllabus_progress": "Progres Silabus",
        "week_num": "Minggu {{num}}",
        "feedback_repeat_eyebrow": "Pemahaman perlu ditingkatkan",
        "feedback_review_eyebrow": "Sesi review ditambahkan",
        "feedback_accelerate_eyebrow": "Anda sangat cepat!",
        "continue_now": "Lanjut sekarang",
        "no_topic_today": "Tidak ada topik hari ini",
        "no_topic_today_desc": "Kamu sudah menyelesaikan semua materi untuk hari ini. Waktu yang tepat untuk beristirahat!",
        "today_topic": "Topik Hari Ini",
        "approx_mins": "~{{duration}} menit",
        "material_progress": "Progress materi",
        "start_learning": "Mulai Belajar",
        "learning_consistency": "Konsistensi Belajar",
        "last_login": "Login terakhir: ",
        "login_learning_activity": "Aktivitas login & belajar",
        "day": "hari",
        "consecutive": "Berturut-turut",
        "personal_record": "Rekor pribadi",
        "active_days_from": "hari aktif dari",
        "last_days": "hari terakhir",
        "total_logins": "total login",
        "login_tomorrow_streak": "💡 Login besok untuk tambah streak. Skip satu hari = ",
        "restart_from_1": "ulang dari 1",
        "login_today_streak": "💡 Login hari ini untuk mulai streak pertamamu.",
        "history": "Riwayat",
        "level_and_xp": "Level & XP",
        "xp_from_mastery": "XP dari mastery topik",
        "xp_history": "Riwayat XP",
        "total_xp": "total XP",
        "remaining": "Sisa",
        "xp_for_next_level": "XP untuk naik ke",
        "recent_xp": "XP Terbaru",
        "tip": "Tip:",
        "complete_quizzes_for_xp": "Selesaikan kuis topik untuk naikin mastery → XP.",
        "rag_quality": "Kualitas RAG",
        "ragas_auto": "RAGAS — otomatis per pesan",
        "no_messages": "Belum ada pesan ke Tutor AI.",
        "waiting_ragas": "Menunggu penilaian RAGAS…",
        "score_auto": "Skor akan muncul otomatis setiap kali Tutor AI menjawab.",
        "messages_scored": "{{scored}} dari {{total}} pesan dinilai · RAGAS otomatis",
        "needs_check": "perlu dicek",
        "faithfulness": "Faithfulness",
        "relevancy": "Answer Relevancy",
        "faithfulness_tooltip": "Seberapa konsisten jawaban Tutor dengan konteks yang di-retrieve",
        "relevancy_tooltip": "Seberapa relevan jawaban Tutor dengan pertanyaan user",
        "session_avg": "Rata-rata sesi ini"
    }
}

en_additions = {
    "dashboard": {
        "morning": "Good morning",
        "afternoon": "Good afternoon",
        "evening": "Good evening",
        "night": "Good night",
        "ready": "Ready to continue your learning journey today?",
        "streak": "Streak",
        "days": "Days",
        "level": "Level",
        "chapter_start": "Chapter 01 — Start",
        "start_journey": "Start your",
        "learning": "journey",
        "no_session_desc": "No active session. Create your first curriculum and let Planner Agent build a personalized learning path for you.",
        "create_curriculum": "Create Curriculum",
        "passed": "Passed",
        "all_topics": "All topics",
        "finished": "are finished",
        "all_topics_desc": "You have completed all available materials. It is time to review or start a new topic.",
        "start_new_topic": "Start New Topic",
        "chapter_continue": "Chapter {{num}} — Continue",
        "topics_count": "{{completed}} / {{total}} topics",
        "mins": "{{duration}} minutes",
        "percent_finished": "{{progress}}% finished",
        "continue_learning": "Continue Learning",
        "start_now": "Start Now",
        "view_curriculum": "View Curriculum",
        "next_topic": "Next topic",
        "done": "Done",
        "quiz": "Quiz",
        "chat": "Chat",
        "history_activity": "History · Activity",
        "recent_activity": "Recent Activity",
        "view_all": "View all",
        "no_activity": "No activity yet",
        "no_activity_desc": "Start learning to see your activity history here. Complete a module or take a quiz to start populating your history.",
        "syllabus_progress": "Syllabus Progress",
        "week_num": "Week {{num}}",
        "feedback_repeat_eyebrow": "Understanding needs improvement",
        "feedback_review_eyebrow": "Review session added",
        "feedback_accelerate_eyebrow": "You are very fast!",
        "continue_now": "Continue now",
        "no_topic_today": "No topic today",
        "no_topic_today_desc": "You have completed all materials for today. Perfect time to rest!",
        "today_topic": "Today's Topic",
        "approx_mins": "~{{duration}} mins",
        "material_progress": "Material progress",
        "start_learning": "Start Learning",
        "learning_consistency": "Learning Consistency",
        "last_login": "Last login: ",
        "login_learning_activity": "Login & learning activity",
        "day": "days",
        "consecutive": "Consecutive",
        "personal_record": "Personal record",
        "active_days_from": "active days out of",
        "last_days": "last days",
        "total_logins": "total logins",
        "login_tomorrow_streak": "💡 Login tomorrow to increase streak. Skip one day = ",
        "restart_from_1": "restart from 1",
        "login_today_streak": "💡 Login today to start your first streak.",
        "history": "History",
        "level_and_xp": "Level & XP",
        "xp_from_mastery": "XP from topic mastery",
        "xp_history": "XP History",
        "total_xp": "total XP",
        "remaining": "Remaining",
        "xp_for_next_level": "XP for next level",
        "recent_xp": "Recent XP",
        "tip": "Tip:",
        "complete_quizzes_for_xp": "Complete topic quizzes to increase mastery → XP.",
        "rag_quality": "RAG Quality",
        "ragas_auto": "RAGAS — automatic per message",
        "no_messages": "No messages to Tutor AI yet.",
        "waiting_ragas": "Waiting for RAGAS evaluation…",
        "score_auto": "Scores will appear automatically every time Tutor AI replies.",
        "messages_scored": "{{scored}} of {{total}} messages scored · RAGAS auto",
        "needs_check": "needs checking",
        "faithfulness": "Faithfulness",
        "relevancy": "Answer Relevancy",
        "faithfulness_tooltip": "How consistent the Tutor's answer is with the retrieved context",
        "relevancy_tooltip": "How relevant the Tutor's answer is to the user's question",
        "session_avg": "Session average"
    }
}

def update_file(filepath, additions):
    with open(filepath, 'r') as f:
        data = json.load(f)
    for key, val in additions.items():
        if key in data and isinstance(data[key], dict) and isinstance(val, dict):
            data[key].update(val)
        else:
            data[key] = val
    with open(filepath, 'w') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

update_file(ID_FILE, id_additions)
update_file(EN_FILE, en_additions)
print("done dashboard")
